<?php

/*
 * RELEASED AS GNU General Public License v3 (GPL-3)
 * http://www.gnu.org/licenses/quick-guide-gplv3.html
 *
 * Originally written by Tim R. Havens 2015-01-27 please track changes below
 *
 */

return (object) array(
   'php_exec_path'      => '/usr/bin/php',
   'www_root'           => '/var/www/html/driveby_new/',
   'data_storage_local' => '/disk1/driveby_data/',
   'data_storage_nfs'   => '/mnt/nfs/disk1/driveby_data/',
   'rtl_power_path'     => '/usr/local/bin/rtl_power',
   'http_gui_host'      => '10.0.1.2',
   'http_gui_remote'    => '10.0.1.4',

   'gps' => array( 0 => (object) array('device'                   => 0,
                                       'lat_default'              => 37.85952333,
                                       'long_default'             => -90.59005333,
                                       'data_out'                 => '/disk1/driveby_data/gps_0_data.out',
                                       'data_out_local'           => '/disk1/driveby_data/gps_0_data.out',
                                       'log_all_data_out'         => '/disk1/driveby_data/gps_0_log_all_data.out',
                                       'log_all_data_out_local'   => '/disk1/driveby_data/gps_0_log_all_data.out',
                                       'az_el_out'                => '/disk1/driveby_data/gps_0_az_el.out',
                                       'az_el_out_local'          => '/disk1/driveby_data/gps_0_az_el.out',
                                       'dop_out'                  => '/disk1/driveby_data/gps_0_dop.out',
                                       'dop_out_local'            => '/disk1/driveby_data/gps_0_dop.out',
                                       'system_stat_out'          => '/disk1/driveby_data/gps_0.out',
                                       'system_stat_all_data_out' => '/disk1/driveby_data/gps_0_log_all_data.out',
                                       'hostname'                 => '10.0.1.2')
                  ),

   'rtl' => array( 0 => (object) array('device'         => 0,
                                       'mhz'            => 44,
                                       'freq_start'     => 44250000,
                                       'freq_stop'      => 44265000,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_0_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_0_data.out',
                                       'data_out_file'  => 'rtl_0_data.out',
                                       'hostname'       => '10.0.1.4'),
                   1 => (object) array('device'         => 1,
                                       'mhz'            => 50,
                                       'freq_start'     => 50090000,
                                       'freq_stop'      => 50105000,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_1_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_1_data.out',
                                       'data_out_file'  => 'rtl_1_data.out',
                                       'hostname'       => '10.0.1.4'),
                   2 => (object) array('device'         => 2,
                                       'mhz'            => 144,
                                       'freq_start'     => 144200000,
                                       'freq_stop'      => 144215000,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_2_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_2_data.out',
                                       'data_out_file'  => 'rtl_2_data.out',
                                       'hostname'       => '10.0.1.4'),
                   3 => (object) array('device'         => 3,
                                       'mhz'            => 222,
                                       'freq_start'     => 222200000,
                                       'freq_stop'      => 222215000,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_3_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_3_data.out',
                                       'data_out_file'  => 'rtl_3_data.out',
                                       'hostname'       => '10.0.1.4'),
                   4 => (object) array('device'         => 4,
                                       'mhz'            => 432,
                                       'freq_start'     => 432100000,
                                       'freq_stop'      => 432115000,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_4_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_4_data.out',
                                       'data_out_file'  => 'rtl_4_data.out',
                                       'hostname'       => '10.0.1.4'),
                   5 => (object) array('device'         => 5,
                                       'mhz'            => 0,
                                       'freq_start'     => 0,
                                       'freq_stop'      => 0,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_5_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_5_data.out',
                                       'data_out_file'  => 'rtl_5_data.out',
                                       'hostname'       => '10.0.1.4'),
                   6 => (object) array('device'         => 6,
                                       'mhz'            => 0,
                                       'freq_start'     => 0,
                                       'freq_stop'      => 0,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_6_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_6_data.out',
                                       'data_out_file'  => 'rtl_6_data.out',
                                       'hostname'       => '10.0.1.4'),
                   7 => (object) array('device'         => 7,
                                       'mhz'            => 0,
                                       'freq_start'     => 0,
                                       'freq_stop'      => 0,
                                       'bw'             => '15k',
                                       'integration'    => 1,
                                       'gain'           => 10,
                                       'window'         => 'blackman',
                                       'fir_size'       => 7,
                                       'crop_percent'   => '20%',
                                       'data_out'       => '/mnt/nfs/disk1/driveby_data/rtl_7_data.out',
                                       'data_out_local' => '/disk1/driveby_data/rtl_7_data.out',
                                       'data_out_file'  => 'rtl_7_data.out',
                                       'hostname'       => '10.0.1.4'),

                  ),
);