<?php
/*
Copyright 2014 Johan Desmyter <johan@etic.yt>

This file is part of nykopol/gpsd-client.

nykopol/gpsd-client is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

nykopol/gpsd-client is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with nykopol/gpsd-client. If not, see http://www.gnu.org/licenses/
*/

namespace Nykopol\GpsdClient;

/**
 * GPSD Client exceptions
 */
class Exception extends \Exception
{

}
